# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

RHLightResponseCostC <- function(theta, flux, sdFlux, parameterPrior, sdParameterPrior, Rg, VPD, Temp, VPD0, fixVPD) {
    .Call('_REddyProc_RHLightResponseCostC', PACKAGE = 'REddyProc', theta, flux, sdFlux, parameterPrior, sdParameterPrior, Rg, VPD, Temp, VPD0, fixVPD)
}

whichValueGreaterEqualC <- function(x, threshold, iStart) {
	# TODO 1 somtheing wrong when directly importing
    # .Call('_REddyProc_whichValueGreaterEqualC', PACKAGE = 'REddyProc', x, threshold, iStart)
	idx <- which(x[iStart:length(x)] >= threshold)
	if (length(idx) == 0) return(NA_integer_)
	idx[1] + iStart - 1L
}

